import { Injectable } from '@angular/core';
import { from, Observable, of } from 'rxjs';
import { Maquette } from '../types';
import { delay, map } from 'rxjs/operators';

const mockApi = [
  {
    inProduction: false,
    _id: '5cf3da573839b7199778af1c',
    schoolYear: '2018/2019',
    master: {
      maquettes: ['5cf3da573839b7199778af1c'],
      _id: '5cf3da3c3839b7199778af1b',
      name: 'Master III',
      description: 'Un master en alternance informatique',
      __v: 0,
      id: '5cf3da3c3839b7199778af1b',
    },
    years: [
      {
        semesters: [
          {
            modules: [
              {
                courses: [
                  {
                    lengthExam: 0,
                    commun: '',
                    _id: '5cf3da573839b7199778af3d',
                    name: 'Bases de données (SQL)',
                    nmbGroupTd: 1,
                    nmbAmphiHour: 12,
                    nmbTdHour: 12,
                    coefCC: 50,
                    coefExam: 50,
                    nmbEcts: 3,
                    examType: 'Pdt cours',
                    courseEnglish: false,
                    englishTranslation: 'Advanced databases',
                    ratrappage: true,
                    totalProf: 24,
                    totalEtu: 24,
                    id: '5cf3da573839b7199778af3d',
                  },
                  {
                    lengthExam: 2,
                    commun: '',
                    _id: '5cf3da573839b7199778af3c',
                    name: 'Intelligence artificielle',
                    nmbGroupTd: 1,
                    nmbAmphiHour: 12,
                    nmbTdHour: 12,
                    coefCC: 50,
                    coefExam: 50,
                    nmbEcts: 3,
                    examType: 'Ecrit',
                    courseEnglish: false,
                    englishTranslation: '',
                    ratrappage: true,
                    totalProf: 24,
                    totalEtu: 24,
                    id: '5cf3da573839b7199778af3c',
                  },
                  {
                    lengthExam: 2,
                    commun: '',
                    _id: '5cf3da573839b7199778af3b',
                    name: 'Réseaux',
                    nmbGroupTd: 1,
                    nmbAmphiHour: 12,
                    nmbTdHour: 12,
                    coefCC: 50,
                    coefExam: 50,
                    nmbEcts: 3,
                    examType: 'Ecrit',
                    courseEnglish: false,
                    englishTranslation: 'Networks',
                    ratrappage: true,
                    totalProf: 24,
                    totalEtu: 24,
                    id: '5cf3da573839b7199778af3b',
                  },
                ],
                _id: '5cf3da573839b7199778af3a',
                name: 'UE : M701',
                ects: 9,
                totalEtu: 72,
                totalTD: 3,
                totalAmphi: 36,
                totalExam: 4,
                id: '5cf3da573839b7199778af3a',
              },
              {
                courses: [
                  {
                    lengthExam: 2,
                    commun: '',
                    _id: '5cf3da573839b7199778af39',
                    name: "Conception d'applications réparties 1",
                    nmbGroupTd: 1,
                    nmbAmphiHour: 12,
                    nmbTdHour: 12,
                    coefCC: 50,
                    coefExam: 50,
                    nmbEcts: 3,
                    examType: 'sur PC',
                    courseEnglish: false,
                    englishTranslation: 'NET programming 1',
                    ratrappage: true,
                    totalProf: 24,
                    totalEtu: 24,
                    id: '5cf3da573839b7199778af39',
                  },
                  {
                    lengthExam: 0,
                    commun: '',
                    _id: '5cf3da573839b7199778af38',
                    name: 'C++',
                    nmbGroupTd: 1,
                    nmbAmphiHour: 12,
                    nmbTdHour: 12,
                    coefCC: 100,
                    coefExam: 0,
                    nmbEcts: 4,
                    examType: '',
                    courseEnglish: false,
                    englishTranslation: 'C++ programming',
                    ratrappage: false,
                    totalProf: 24,
                    totalEtu: 24,
                    id: '5cf3da573839b7199778af38',
                  },
                  {
                    lengthExam: 2,
                    commun: '',
                    _id: '5cf3da573839b7199778af37',
                    name: 'JEE 1',
                    nmbGroupTd: 1,
                    nmbAmphiHour: 12,
                    nmbTdHour: 12,
                    coefCC: 50,
                    coefExam: 50,
                    nmbEcts: 3,
                    examType: 'Ecrit',
                    courseEnglish: false,
                    englishTranslation: 'JEE programming',
                    ratrappage: true,
                    totalProf: 24,
                    totalEtu: 24,
                    id: '5cf3da573839b7199778af37',
                  },
                ],
                _id: '5cf3da573839b7199778af36',
                name: 'UE : M702',
                ects: 10,
                totalEtu: 72,
                totalTD: 3,
                totalAmphi: 36,
                totalExam: 4,
                id: '5cf3da573839b7199778af36',
              },
              {
                courses: [
                  {
                    lengthExam: 0,
                    commun: '',
                    _id: '5cf3da573839b7199778af35',
                    name: 'Projet de groupe',
                    nmbGroupTd: 1,
                    nmbAmphiHour: 0,
                    nmbTdHour: 20,
                    coefCC: 100,
                    coefExam: 0,
                    nmbEcts: 3,
                    examType: '',
                    courseEnglish: false,
                    englishTranslation: 'Group projects',
                    ratrappage: false,
                    totalProf: 20,
                    totalEtu: 20,
                    id: '5cf3da573839b7199778af35',
                  },
                  {
                    lengthExam: 0,
                    commun: '',
                    _id: '5cf3da573839b7199778af34',
                    name: "Jeu d'entreprise",
                    nmbGroupTd: 1,
                    nmbAmphiHour: 0,
                    nmbTdHour: 18,
                    coefCC: 100,
                    coefExam: 0,
                    nmbEcts: 2,
                    examType: '',
                    courseEnglish: false,
                    englishTranslation: 'Business Game',
                    ratrappage: false,
                    totalProf: 18,
                    totalEtu: 18,
                    id: '5cf3da573839b7199778af34',
                  },
                  {
                    lengthExam: 2,
                    commun: '',
                    _id: '5cf3da573839b7199778af33',
                    name: "Marketing appliqué à l'informatique",
                    nmbGroupTd: 1,
                    nmbAmphiHour: 12,
                    nmbTdHour: 12,
                    coefCC: 60,
                    coefExam: 40,
                    nmbEcts: 2,
                    examType: 'ecrit',
                    courseEnglish: false,
                    englishTranslation: '',
                    ratrappage: true,
                    totalProf: 24,
                    totalEtu: 24,
                    id: '5cf3da573839b7199778af33',
                  },
                  {
                    lengthExam: 0,
                    commun: '',
                    _id: '5cf3da573839b7199778af32',
                    name: 'Anglais',
                    nmbGroupTd: 1,
                    nmbAmphiHour: 10,
                    nmbTdHour: 12,
                    coefCC: 100,
                    coefExam: 0,
                    nmbEcts: 3,
                    examType: '',
                    courseEnglish: true,
                    englishTranslation: 'English',
                    ratrappage: false,
                    totalProf: 22,
                    totalEtu: 22,
                    id: '5cf3da573839b7199778af32',
                  },
                  {
                    lengthExam: 0,
                    commun: '',
                    _id: '5cf3da573839b7199778af31',
                    name: 'Développement personnel',
                    nmbGroupTd: 1,
                    nmbAmphiHour: 0,
                    nmbTdHour: 7,
                    coefCC: 100,
                    coefExam: 0,
                    nmbEcts: 1,
                    examType: '',
                    courseEnglish: false,
                    englishTranslation: 'Personal development',
                    ratrappage: false,
                    totalProf: 7,
                    totalEtu: 7,
                    id: '5cf3da573839b7199778af31',
                  },
                ],
                _id: '5cf3da573839b7199778af30',
                name: 'UE : M703',
                ects: 11,
                totalEtu: 91,
                totalTD: 5,
                totalAmphi: 22,
                totalExam: 2,
                id: '5cf3da573839b7199778af30',
              },
            ],
            _id: '5cf3da573839b7199778af2f',
            number: 1,
            totalEtu: 235,
            ects: 30,
            totalTD: 11,
            totalAmphi: 94,
            totalExam: 10,
            id: '5cf3da573839b7199778af2f',
          },
          {
            modules: [
              {
                courses: [
                  {
                    lengthExam: 2,
                    commun: '',
                    _id: '5cf3da573839b7199778af2e',
                    name: 'Aide à la décision',
                    nmbGroupTd: 1,
                    nmbAmphiHour: 12,
                    nmbTdHour: 12,
                    coefCC: 50,
                    coefExam: 50,
                    nmbEcts: 2,
                    examType: 'Ecrit',
                    courseEnglish: false,
                    englishTranslation: '',
                    ratrappage: true,
                    totalProf: 24,
                    totalEtu: 24,
                    id: '5cf3da573839b7199778af2e',
                  },
                  {
                    lengthExam: 2,
                    commun: '',
                    _id: '5cf3da573839b7199778af2d',
                    name: 'BI / Big Data',
                    nmbGroupTd: 1,
                    nmbAmphiHour: 12,
                    nmbTdHour: 12,
                    coefCC: 50,
                    coefExam: 50,
                    nmbEcts: 3,
                    examType: 'Pdt cours',
                    courseEnglish: false,
                    englishTranslation: 'BI / Big Data',
                    ratrappage: true,
                    totalProf: 24,
                    totalEtu: 24,
                    id: '5cf3da573839b7199778af2d',
                  },
                  {
                    lengthExam: 2,
                    commun: '',
                    _id: '5cf3da573839b7199778af2c',
                    name: "Management de l'innovation",
                    nmbGroupTd: 1,
                    nmbAmphiHour: 12,
                    nmbTdHour: 12,
                    coefCC: 100,
                    coefExam: 0,
                    nmbEcts: 2,
                    examType: '',
                    courseEnglish: false,
                    englishTranslation: '',
                    ratrappage: true,
                    totalProf: 24,
                    totalEtu: 24,
                    id: '5cf3da573839b7199778af2c',
                  },
                ],
                _id: '5cf3da573839b7199778af2b',
                name: 'UE : M801',
                ects: 7,
                totalEtu: 72,
                totalTD: 3,
                totalAmphi: 36,
                totalExam: 6,
                id: '5cf3da573839b7199778af2b',
              },
              {
                courses: [
                  {
                    lengthExam: 2,
                    commun: '',
                    _id: '5cf3da573839b7199778af2a',
                    name: 'Aide à la décision',
                    nmbGroupTd: 1,
                    nmbAmphiHour: 12,
                    nmbTdHour: 12,
                    coefCC: 50,
                    coefExam: 50,
                    nmbEcts: 2,
                    examType: 'Ecrit',
                    courseEnglish: false,
                    englishTranslation: 'Group project',
                    ratrappage: true,
                    totalProf: 24,
                    totalEtu: 24,
                    id: '5cf3da573839b7199778af2a',
                  },
                ],
                _id: '5cf3da573839b7199778af29',
                name: 'UE : M802',
                ects: 2,
                totalEtu: 24,
                totalTD: 1,
                totalAmphi: 12,
                totalExam: 2,
                id: '5cf3da573839b7199778af29',
              },
              {
                courses: [
                  {
                    lengthExam: 2,
                    commun: '',
                    _id: '5cf3da573839b7199778af28',
                    name: 'Aide à la décision',
                    nmbGroupTd: 1,
                    nmbAmphiHour: 12,
                    nmbTdHour: 12,
                    coefCC: 50,
                    coefExam: 50,
                    nmbEcts: 2,
                    examType: 'Ecrit',
                    courseEnglish: false,
                    englishTranslation: 'Group project',
                    ratrappage: true,
                    totalProf: 24,
                    totalEtu: 24,
                    id: '5cf3da573839b7199778af28',
                  },
                ],
                _id: '5cf3da573839b7199778af27',
                name: 'UE : M803',
                ects: 2,
                totalEtu: 24,
                totalTD: 1,
                totalAmphi: 12,
                totalExam: 2,
                id: '5cf3da573839b7199778af27',
              },
              {
                courses: [
                  {
                    lengthExam: 2,
                    commun: '',
                    _id: '5cf3da573839b7199778af26',
                    name: 'Aide à la décision',
                    nmbGroupTd: 1,
                    nmbAmphiHour: 12,
                    nmbTdHour: 12,
                    coefCC: 50,
                    coefExam: 50,
                    nmbEcts: 2,
                    examType: 'Ecrit',
                    courseEnglish: false,
                    englishTranslation: 'Group project',
                    ratrappage: true,
                    totalProf: 24,
                    totalEtu: 24,
                    id: '5cf3da573839b7199778af26',
                  },
                ],
                _id: '5cf3da573839b7199778af25',
                name: 'UE : M804',
                ects: 2,
                totalEtu: 24,
                totalTD: 1,
                totalAmphi: 12,
                totalExam: 2,
                id: '5cf3da573839b7199778af25',
              },
            ],
            _id: '5cf3da573839b7199778af24',
            number: 2,
            totalEtu: 144,
            ects: 13,
            totalTD: 6,
            totalAmphi: 72,
            totalExam: 12,
            id: '5cf3da573839b7199778af24',
          },
        ],
        extras: [
          {
            items: [
              {
                hour: 2,
                _id: '5cf3da573839b7199778af3f',
                name: 'Rentrée',
                date: '17/09 Matin',
              },
            ],
            _id: '5cf3da573839b7199778af3e',
            name: 'Integration',
            totalHour: 2,
            id: '5cf3da573839b7199778af3e',
          },
        ],
        _id: '5cf3da573839b7199778af23',
        level: 'Master 1',
        totalHour: 403,
        id: '5cf3da573839b7199778af23',
      },
      {
        semesters: [
          {
            modules: [
              {
                courses: [
                  {
                    lengthExam: 2,
                    commun: '',
                    _id: '5cf3da573839b7199778af20',
                    name: 'Projet de groupe',
                    nmbGroupTd: 1,
                    nmbAmphiHour: 20,
                    nmbTdHour: 10,
                    coefCC: 30,
                    coefExam: 70,
                    nmbEcts: 2,
                    examType: 'Soutenance + dossier',
                    courseEnglish: false,
                    englishTranslation: 'Group project',
                    ratrappage: false,
                    totalProf: 30,
                    totalEtu: 30,
                    id: '5cf3da573839b7199778af20',
                  },
                ],
                _id: '5cf3da573839b7199778af1f',
                name: 'UE : M801',
                ects: 2,
                totalEtu: 30,
                totalTD: 1,
                totalAmphi: 20,
                totalExam: 2,
                id: '5cf3da573839b7199778af1f',
              },
            ],
            _id: '5cf3da573839b7199778af1e',
            number: 2,
            totalEtu: 30,
            ects: 2,
            totalTD: 1,
            totalAmphi: 20,
            totalExam: 2,
            id: '5cf3da573839b7199778af1e',
          },
        ],
        extras: [
          {
            items: [
              {
                hour: 2,
                _id: '5cf3da573839b7199778af22',
                name: 'Rentrée',
                date: '17/09 Matin',
              },
            ],
            _id: '5cf3da573839b7199778af21',
            name: 'Integration',
            totalHour: 2,
            id: '5cf3da573839b7199778af21',
          },
        ],
        _id: '5cf3da573839b7199778af1d',
        level: 'Master 2',
        totalHour: 34,
        id: '5cf3da573839b7199778af1d',
      },
    ],
    __v: 0,
    id: '5cf3da573839b7199778af1c',
  },
];

@Injectable({
  providedIn: 'root',
})
export class MaquetteService {
  constructor() {}

  getAll(): Observable<Maquette[]> {
    return from([mockApi]).pipe(
      delay(300),
      map(arr => arr.map(Maquette.fromJs)),
    );
  }
}
